language: ruby
rvm:
  - 2.5.1

before_install:
  - gem update bundler

before_script:
- sudo apt-get update -qq
- sudo -u postgres psql -c "create database jps_test;"
- bundle exec rake db:migrate test

script: bundle exec rake test
